{% set name = "lissero" %}
{% set version = "0.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 602a3c69ff378f508c62bc0784e846fc052c19c824b51192568d3a56533c77a1

build:
  noarch: python
  number: 0
  entry_points:
    - lissero = lissero.run_lissero:run_lissero
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - loguru
    - biopython
    - ispcr

test:
  imports:
    - lissero
    - lissero.scripts
  commands:
    - lissero --help

about:
  home: "https://github.com/MDU-PHL/lissero"
  license: GPL-3.0+
  license_family: GPL
  license_file: "LICENSE"
  summary: "In silico serotyping of Listeria monocytogenes"
  doc_url: "https://github.com/MDU-PHL/LisSero/blob/master/README.md"
  dev_url: "https://github.com/MDU-PHL/lissero"

extra:
  recipe-maintainers:
    - andersgs
    - abcdtree
