build:
  number: 0
  skip: True # [osx]

package:
  name: scrm
  version: "1.7.3"

source:
  url: https://github.com/scrm/scrm/releases/download/v1.7.3/scrm-x64-static.tar.gz
  sha256: eaad5a16640f06e97df637e7d9fc67de7614c3337fc77cb40c17d01d01a9100e

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - scrm 2 1 -T > /dev/null

about:
  home: https://scrm.github.io/
  summary: A coalescent simulator for genome-scale sequences
  license: GNU General Public License v3 or later (GPLv3+)
