{% set name = "ngmaster" %}
{% set version = "0.5.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 43f603a1f1fda41a59f175d56dd06bba9754e90f0b754862a6f1a05b8b37cae0

build:
  number: 0
  noarch: python
  entry_points:
    - ngmaster=ngmaster.run_ngmaster:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - biopython
    - bs4
    - pip
    - requests
  run:
    - python >=3.6
    - biopython
    - bs4
    - requests
    - ispcr

test:
  imports:
    - ngmaster
  commands:
    - ngmaster --help

about:
  home: "https://github.com/MDU-PHL/ngmaster"
  license: "GNU General Public v2 (GPLv2)"
  license_family: "GPL2"
  license_file: ""
  summary: "In silico multi-antigen sequence typing for Neisseria gonorrhoeae (NG-MAST)"
  doc_url: "https://github.com/MDU-PHL/ngmaster/blob/master/README.md"
  dev_url: "https://github.com/MDU-PHL/ngmaster"

extra:
  recipe-maintainers:
    - andersgs
